[package]
name = "gbce"
version = "0.1.0"
authors = ["Nicholas Londey <nicholas@londey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"
# sdl2_ttf = "0.25.1"
serde = "1.0"
serde_json = "1.0"
